--
-- PostgreSQL database dump
--

\restrict QkfSRo2TL9ZAWSlLqwxQ3TuIbSWiehoFrUWdWJxYuUzcsUty2w8jkLH088tU45H

-- Dumped from database version 16.15 (Postgres.app)
-- Dumped by pg_dump version 16.15 (Postgres.app)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: movie_data; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.movie_data (
    data_id integer NOT NULL,
    movie_id integer NOT NULL,
    data_kind text NOT NULL,
    seq integer DEFAULT 0 NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT movie_data_kind_allowed CHECK ((data_kind = ANY (ARRAY['mood_feel'::text, 'theme'::text, 'premise'::text, 'plot_scene'::text]))),
    CONSTRAINT movie_data_not_blank CHECK ((length(btrim(content)) > 0))
);


--
-- Name: movie_data_data_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.movie_data ALTER COLUMN data_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movie_data_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: movie_vectors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.movie_vectors (
    vector_id integer NOT NULL,
    data_id integer NOT NULL,
    embed_variant text NOT NULL,
    embedding public.vector(1024) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: movie_vectors_vector_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.movie_vectors ALTER COLUMN vector_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movie_vectors_vector_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: movies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.movies (
    movie_id integer NOT NULL,
    title text NOT NULL,
    release_date date,
    runtime_minutes integer,
    tmdb_id text NOT NULL,
    tmdb_overview text,
    wikidata_id text,
    wikidata_plot text,
    tmdb_raw_payload jsonb NOT NULL,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: movies_movie_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.movies ALTER COLUMN movie_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movies_movie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: movie_data movie_data_one_per_slot; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movie_data
    ADD CONSTRAINT movie_data_one_per_slot UNIQUE (movie_id, data_kind, seq);


--
-- Name: movie_data movie_data_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movie_data
    ADD CONSTRAINT movie_data_pkey PRIMARY KEY (data_id);


--
-- Name: movie_vectors movie_vectors_one_per_variant; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movie_vectors
    ADD CONSTRAINT movie_vectors_one_per_variant UNIQUE (data_id, embed_variant);


--
-- Name: movie_vectors movie_vectors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movie_vectors
    ADD CONSTRAINT movie_vectors_pkey PRIMARY KEY (vector_id);


--
-- Name: movies movies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movies
    ADD CONSTRAINT movies_pkey PRIMARY KEY (movie_id);


--
-- Name: movies movies_tmdb_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movies
    ADD CONSTRAINT movies_tmdb_id_key UNIQUE (tmdb_id);


--
-- Name: movies movies_wikidata_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movies
    ADD CONSTRAINT movies_wikidata_id_key UNIQUE (wikidata_id);


--
-- Name: movie_data_kind_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX movie_data_kind_idx ON public.movie_data USING btree (data_kind);


--
-- Name: movie_data_movie_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX movie_data_movie_idx ON public.movie_data USING btree (movie_id);


--
-- Name: movie_vectors_variant_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX movie_vectors_variant_idx ON public.movie_vectors USING btree (embed_variant);


--
-- Name: movie_data movie_data_movie_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movie_data
    ADD CONSTRAINT movie_data_movie_id_fkey FOREIGN KEY (movie_id) REFERENCES public.movies(movie_id) ON DELETE CASCADE;


--
-- Name: movie_vectors movie_vectors_data_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movie_vectors
    ADD CONSTRAINT movie_vectors_data_id_fkey FOREIGN KEY (data_id) REFERENCES public.movie_data(data_id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict QkfSRo2TL9ZAWSlLqwxQ3TuIbSWiehoFrUWdWJxYuUzcsUty2w8jkLH088tU45H

