"""
build_docs.py — render the markdown docs to HTML, so there is ONE source.

THE PROBLEM THIS EXISTS TO KILL
    docs/ held HTML copies of the markdown, kept in step by hand. On 30 Aug 2026 the
    markdown described four agent tools, a semantic layer, a React front end and 37
    tests; the HTML still described a system from ten days earlier. Nobody lied — the
    second copy simply drifted, the way second copies do.

    Same failure as REGION being defined in two files, and as the test environment
    being typed out instead of read from the code. A fact written down twice will
    eventually disagree with itself.

    So the markdown is the source and the HTML is derived — like the knowledge graph
    from raw_payload, or static/ from frontend/. Derived files are disposable and are
    never edited by hand.

WHAT IS **NOT** GENERATED
    The six diagram pages — ARCHITECTURE, CONCEPT-MAP, PASS-0/1/2-DIAGRAM, PASS-GROWTH —
    have no markdown source. They are drawings, not prose, and stay hand-built. They
    are not duplicates of anything, so they cannot drift in this way.

RUN IT
    python -m scripts.build_docs            write the HTML
    python -m scripts.build_docs --check    fail if a page is out of date (CI runs this)

Standard library only, on purpose. A gate that needs a dependency install can be
broken BY a dependency — the same rule repo_check.py follows.
"""

import html as html_module
import os
import re
import sys

# scripts/ is one level below the repository root; every path in PAGES is
# relative to the root, so go there once.
os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# source markdown -> generated HTML. Anything not listed here is hand-built.
PAGES = [
    ("README.md",                   "README.html"),
    ("docs/decisions.md",           "docs/DECISIONS.html"),
    ("docs/session-notes.md",       "docs/SESSION-NOTES.html"),
    ("docs/retrieval-pipeline.md",  "docs/RETRIEVAL-PIPELINE.html"),
    ("docs/interview-bridges.md",   "docs/INTERVIEW-BRIDGES.html"),
    ("docs/third-party.md",         "docs/THIRD-PARTY.html"),
    ("docs/verifying-code.md",      "docs/VERIFYING-CODE.html"),
    ("docs/verification.md",        "docs/VERIFICATION.html"),
    ("docs/change-guard.md",        "docs/CHANGE-GUARD.html"),
    ("docs/roadmap.md",             "docs/ROADMAP.html"),
]

BANNER = ("<!-- GENERATED BY build_docs.py FROM {source} — DO NOT EDIT THIS FILE.\n"
          "     Edit the markdown and run: python -m scripts.build_docs -->")


# ─────────────────────────────────────────────────────── inline formatting

def inline(text):
    """`code`, **bold**, *italic*, [links] — in that order, and code first.

    Code spans are lifted out before anything else touches them, or a snippet
    containing an asterisk gets turned into italics inside a code block.
    """
    spans = []

    def stash(match):
        spans.append(match.group(1))
        return f"\x00{len(spans) - 1}\x00"

    text = re.sub(r"`([^`]+)`", stash, text)
    text = html_module.escape(text, quote=False)
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', text)
    # non-greedy, and NOT [^*]+ — bold often wraps an italic:
    #   **The walls were about the *vendor*, not the model**
    # A pattern that forbids inner asterisks leaves both markers on the page.
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"(?<![*\w])\*([^*\n]+)\*(?!\*)", r"<em>\1</em>", text)
    for index, code in enumerate(spans):
        text = text.replace(f"\x00{index}\x00",
                            f"<code>{html_module.escape(code, quote=False)}</code>")
    return text


def slug(text):
    return re.sub(r"[^a-z0-9]+", "-", re.sub(r"<[^>]+>", "", text).lower()).strip("-")


# ─────────────────────────────────────────────────────── block rendering

def render(markdown):
    out, lines, i = [], markdown.replace("\r\n", "\n").split("\n"), 0
    open_list = None

    def close_list():
        nonlocal open_list
        if open_list:
            out.append(f"</{open_list}>")
            open_list = None

    while i < len(lines):
        line = lines[i]

        if line.startswith("```"):                              # fenced code
            close_list()
            language = line[3:].strip()
            body, i = [], i + 1
            while i < len(lines) and not lines[i].startswith("```"):
                body.append(lines[i]); i += 1
            i += 1
            css = f' class="lang-{slug(language)}"' if language else ""
            out.append(f"<pre><code{css}>"
                       + html_module.escape("\n".join(body), quote=False) + "</code></pre>")
            continue

        if re.fullmatch(r"\s*(-{3,}|\*{3,}|_{3,})\s*", line):    # horizontal rule
            close_list(); out.append("<hr>"); i += 1; continue

        heading = re.match(r"^(#{1,6})\s+(.*)$", line)
        if heading:
            close_list()
            level, text = len(heading.group(1)), inline(heading.group(2).strip())
            out.append(f'<h{level} id="{slug(text)}">{text}</h{level}>')
            i += 1; continue

        if line.lstrip().startswith("|") and i + 1 < len(lines) \
                and re.fullmatch(r"\s*\|[\s:|-]+\|\s*", lines[i + 1]):
            close_list()
            def cells(row):
                return [c.strip() for c in row.strip().strip("|").split("|")]
            header = cells(line); i += 2
            out.append("<table><thead><tr>"
                       + "".join(f"<th>{inline(c)}</th>" for c in header)
                       + "</tr></thead><tbody>")
            while i < len(lines) and lines[i].lstrip().startswith("|"):
                out.append("<tr>" + "".join(f"<td>{inline(c)}</td>"
                                            for c in cells(lines[i])) + "</tr>")
                i += 1
            out.append("</tbody></table>"); continue

        if line.startswith(">"):                                 # blockquote
            close_list()
            body = []
            while i < len(lines) and lines[i].startswith(">"):
                body.append(lines[i][1:].lstrip()); i += 1
            out.append("<blockquote>" + inline(" ".join(body)) + "</blockquote>")
            continue

        item = re.match(r"^(\s*)([-*+]|\d+[.)])\s+(.*)$", line)
        if item:
            wanted = "ol" if item.group(2)[0].isdigit() else "ul"
            if open_list != wanted:
                close_list(); out.append(f"<{wanted}>"); open_list = wanted
            body = [item.group(3)]
            i += 1
            while i < len(lines) and lines[i].strip() \
                    and not re.match(r"^(\s*)([-*+]|\d+[.)])\s+", lines[i]) \
                    and not lines[i].startswith(("#", "|", "```", ">")):
                body.append(lines[i].strip()); i += 1
            out.append(f"<li>{inline(' '.join(body))}</li>")
            continue

        if not line.strip():
            close_list(); i += 1; continue

        close_list()                                             # paragraph
        body = [line]
        i += 1
        while i < len(lines) and lines[i].strip() \
                and not lines[i].startswith(("#", "|", "```", ">", "---")) \
                and not re.match(r"^(\s*)([-*+]|\d+[.)])\s+", lines[i]):
            body.append(lines[i]); i += 1
        out.append("<p>" + inline(" ".join(body)) + "</p>")

    close_list()
    return "\n".join(out)


# ─────────────────────────────────────────────────────── the page shell
# Colours lifted from the hand-built pages so the generated ones sit beside them
# without looking like a different project.

STYLE = """
  :root{
    --ink:#17262c; --soft:#4a616b; --muted:#7d919a;
    --paper:#f2f0ea; --card:#fff; --line:#dcd7cd; --accent:#1a6f68;
  }
  *{box-sizing:border-box}
  body{margin:0;background:var(--paper);color:var(--ink);
       font:16px/1.62 -apple-system,BlinkMacSystemFont,"Segoe UI",Inter,Roboto,sans-serif}
  .wrap{max-width:1080px;margin:0 auto;padding:44px 22px 90px}
  .stamp{font-size:11px;letter-spacing:.13em;text-transform:uppercase;color:var(--muted);
         margin-bottom:26px}
  h1{font-size:36px;line-height:1.13;margin:8px 0 18px;letter-spacing:-.022em}
  h2{font-size:22px;margin:44px 0 12px;letter-spacing:-.015em;
     padding-bottom:8px;border-bottom:1px solid var(--line)}
  h3{font-size:17px;margin:30px 0 8px;letter-spacing:-.01em}
  h4{font-size:15px;margin:22px 0 6px;color:var(--soft)}
  p{margin:0 0 14px;color:var(--soft)}
  li{margin:0 0 7px;color:var(--soft)}
  ul,ol{margin:0 0 16px;padding-left:22px}
  strong{color:var(--ink);font-weight:650}
  a{color:var(--accent)}
  hr{border:0;border-top:1px solid var(--line);margin:38px 0}
  table{width:100%;border-collapse:collapse;font-size:14.5px;background:var(--card);
        border:1px solid var(--line);border-radius:10px;overflow:hidden;margin:0 0 20px}
  th{text-align:left;font-size:10px;letter-spacing:.13em;text-transform:uppercase;
     color:var(--muted);padding:12px 18px;border-bottom:1px solid var(--line);
     background:#faf8f4;font-weight:600}
  td{border-bottom:1px solid #eeebe4;padding:13px 18px;vertical-align:top;line-height:1.55;
     color:var(--soft)}
  tr:last-child td{border-bottom:0}
  td:first-child{font-weight:650;color:var(--ink)}
  pre{background:#1f2b30;color:#dfe7ea;border-radius:11px;padding:17px 20px;overflow-x:auto;
      font-size:13px;line-height:1.55;margin:0 0 18px}
  code{background:#eae6de;border-radius:4px;padding:1.5px 5px;font-size:13px;
       font-family:ui-monospace,SFMono-Regular,Menlo,monospace}
  pre code{background:none;padding:0;font-size:inherit;color:inherit}
  blockquote{margin:0 0 18px;padding:12px 18px;border-left:3px solid var(--accent);
             background:#e8efee;border-radius:0 8px 8px 0;color:var(--ink)}
  blockquote p{margin:0;color:inherit}
"""


def page(source, body, title):
    return f"""{BANNER.format(source=source)}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html_module.escape(title)}</title>
<style>{STYLE}</style>
</head>
<body>
<div class="wrap">
<div class="stamp">MovieMotions · generated from {html_module.escape(source)}</div>
{body}
</div>
</body>
</html>
"""


def build(source):
    text = open(source, encoding="utf-8").read()
    first = re.search(r"^#\s+(.*)$", text, re.M)
    title = first.group(1).strip() if first else os.path.basename(source)
    return page(source, render(text), title)


def main():
    checking = "--check" in sys.argv
    stale, written = [], []
    for source, target in PAGES:
        if not os.path.exists(source):
            print(f"  ! {source} is missing — skipped")
            continue
        fresh = build(source)
        current = open(target, encoding="utf-8").read() if os.path.exists(target) else None
        if checking:
            if current != fresh:
                stale.append(target)
        elif current != fresh:
            open(target, "w", encoding="utf-8").write(fresh)
            written.append(target)

    if checking:
        if stale:
            print("OUT OF DATE — the markdown changed and the HTML was not rebuilt:")
            for target in stale:
                print(f"    {target}")
            print("\nRun:  python -m scripts.build_docs")
            return 1
        print(f"all {len(PAGES)} generated pages are up to date")
        return 0

    print(f"rebuilt {len(written)} of {len(PAGES)} pages"
          + ("".join(f"\n    {t}" for t in written) if written else " (nothing changed)"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
